#!/bin/bash
link_src () {
	bot_retorno="$LINE\n"
	bot_retorno+="INSTALADOR OFICIAL.\n ⚙️ Soporte : Ubuntu 18.04 - 20.04\n"
	bot_retorno+="Verifica tus Keys : $message_from_first_name $message_from_last_name \n"
	bot_retorno+="$LINE\n"
	bot_retorno+="<code>GHOST</code>\n"
        bot_retorno+="TOCA EN EL LINK PARA COPIAR INSTALADOR.\n"
        bot_retorno+="$LINE\n"
msj_fun
}
